#!/usr/bin/env bash

alias cw=carwow
alias cst='carwow start'
alias csp='carwow stop'
alias crs='carwow restart'
alias cru='carwow run'
alias cbu='carwow run bundle'
alias cbu='carwow run bundle exec'
alias cry='carwow run yarn'
alias cwp='carwow webpack'

