#!/usr/bin/env bash

alias cw=carwow
alias cs='carwow start'
alias cr='carwow run'
alias bu='carwow run bundle'
alias be='carwow run bundle exec'
alias ry='carwow run yarn'
alias cwp='carwow webpack'

alias gca='git commit -v -am'
alias gpr='git pull --rebase'
